# Generated by Django 4.1.1 on 2022-10-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
